name: "Pull Request Validation"

on:
  pull_request:
    branches: [ dev ]
    
env:
  PROJECT_PATH: 'OrderCloud.Catalyst.Tests/OrderCloud.Catalyst.Tests.csproj'

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3
     
    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH }}
      
    - name: 'Increase max user instances'
      run: echo fs.inotify.max_user_instances=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      
    - name: 'Run Unit Tests'
      run: dotnet test ${{ env.PROJECT_PATH }}
